---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-credentials
spec:
  data:
  - secretKey: credentials
    remoteRef:
      key: {{ .Values.keyPath }}
      property: credentials
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStore }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Release.Name }}-credentials