{{- range $val := .Values.createPullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $val.name }}
  labels:
    {{- include "autobot.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $val.dockerconfigjson }}
{{ end -}}