{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "autobot.fullname" . }}
  labels:
    app: {{ include "autobot.fullname" . }}
    {{- include "autobot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "autobot.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "autobot.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}