{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autobot.serviceAccountName" . }}
  labels:
    {{- include "autobot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "autobot.serviceAccountTokenName" . }}
  labels:
      {{- include "autobot.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "autobot.serviceAccountName" . }}
{{- end }}