
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/main.yml

  release:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          registry: harbor.infra.cluster.ionos.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_SECRET }}
      - uses: goreleaser/goreleaser-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
        if: success()
      - run: |
          go run cmd/updater/updater.go --file charts/autobot/Chart.yaml --version ${{ env.RELEASE_VERSION }}
      - uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://harbor.infra.cluster.ionos.com/paasis/helm
          username: ${{ secrets.HARBOR_USERNAME }}
          access-token: ${{ secrets.HARBOR_SECRET }}
          force: true
          chart-folder: charts/autobot
      - uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Autobot ${{ env.RELEASE_VERSION }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()